--no-cache-dir
UKHO/dockerimages pull request #63
Opened 2020-12-09 11:21 UTC by elduddz

2020-12-09 11:26 UTC, elduddz commented on linux/aws/Dockerfile
> +RUN pip3 install --upgrade awscli==1.16.291 --no-cache-dir
```suggestion
RUN pip3 install --no-cache-dir --upgrade awscli==1.16.291
```

2020-12-10 09:47 UTC, eganjs commented
Looks like `linux/awscli/Dockerfile`needs this fix too

2020-12-10 15:59 UTC, elduddz commented
> Looks like `linux/awscli/Dockerfile`needs this fix too

Yer

2020-12-14 09:21 UTC, eganjs approved these changes

2020-12-16 11:30 UTC, eganjs approved these changes

2020-12-18 13:39 UTC, eganjs requested changes

2020-12-18 13:39 UTC, eganjs commented on linux-archive/jdk8-python36/Dockerfile
> -    python3.6-dev=* \
Can you restore this line

2020-12-18 13:47 UTC, elduddz commented on linux-archive/jdk8-python36/Dockerfile
> -    python3.6-dev=* \
ok put back

2020-12-18 13:49 UTC, eganjs approved these changes

2020-12-21 14:23 UTC, merged